#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

NO_MESSAGE=0
COMMIT_EDITMSG_MESSAGES=$(grep -c "^[^#]" $1 || true)

if [[ $COMMIT_EDITMSG_MESSAGES -eg $NO_MESSAGE]];then
    exec < /dev/tty && git cz --hook || true
fi